# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push: 
    branches:
      - master
    tags:
      - 4.8

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dockerhub:
    runs-on: windows-latest
    steps:
    - name: Build and push Docker images
      run: |
        docker login --username andeadlier --password ${{ secrets.dockerHubAccessToken }}
        docker build . --tag andeadlier/dotnet-framework-sdk-with-java:latest
        docker push
